---
deployment:
  tasks:
    - source /home/ztlzpllpqetq/virtualenv/school/3.7/bin/activate && cd /home/ztlzpllpqetq/school
    - pip install -r requirements.txt
    - python manage.py collectstatic --no-input
    - python manage.py migrate
    - touch tmp/restart.txt