# Generated by Django 3.1.7 on 2021-04-03 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_auto_20210403_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffregister',
            name='IFSC',
        ),
        migrations.RemoveField(
            model_name='staffregister',
            name='TC',
        ),
        migrations.RemoveField(
            model_name='staffregister',
            name='account_no',
        ),
        migrations.RemoveField(
            model_name='staffregister',
            name='addhar_no',
        ),
        migrations.RemoveField(
            model_name='staffregister',
            name='addmission_date',
        ),
        migrations.RemoveField(
            model_name='staffregister',
            name='cast',
        ),
        migrations.RemoveField(
            model_name='staffregister',
            name='castcertificate',
        ),
        migrations.RemoveField(
            model_name='staffregister',
            name='role',
        ),
        migrations.RemoveField(
            model_name='staffregister',
            name='schooler_no',
        ),
        migrations.RemoveField(
            model_name='staffregister',
            name='sssid',
        ),
    ]
