# Generated by Django 3.1.7 on 2021-04-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_auto_20210403_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffregister',
            name='address',
            field=models.CharField(default='none', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffregister',
            name='phone',
            field=models.CharField(default='none', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffregister',
            name='subject',
            field=models.CharField(default='none', max_length=10),
            preserve_default=False,
        ),
    ]
