# Generated by Django 3.1.7 on 2021-04-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_auto_20210403_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffregister',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
