# Generated by Django 3.1.7 on 2021-04-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_staffregister_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffregister',
            name='permanent_address',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staffregister',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
