# Generated by Django 3.1.7 on 2021-04-06 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_studentregister_standard'),
        ('staff', '0009_auto_20210403_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='classtimings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timefrom', models.TimeField()),
                ('timeto', models.TimeField()),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.standard')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.subject')),
            ],
        ),
    ]
