# Generated by Django 3.1.7 on 2021-04-10 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_studentregister_phonestatus'),
        ('staff', '0014_auto_20210410_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtimings',
            name='Class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.standard'),
        ),
    ]
