# Generated by Django 3.2 on 2021-04-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0017_studentattendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='managesesstion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
        ),
    ]
