# Generated by Django 3.2 on 2021-04-28 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0018_managesesstion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='managesesstion',
            new_name='managesession',
        ),
    ]
