# Generated by Django 3.2 on 2021-04-28 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0019_rename_managesesstion_managesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='staff.managesession'),
            preserve_default=False,
        ),
    ]
