# Generated by Django 3.2 on 2021-04-29 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_studentregister_gender'),
        ('staff', '0020_studentattendance_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentattendance',
            name='session',
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentregister'),
        ),
        migrations.DeleteModel(
            name='managesession',
        ),
    ]
