# Generated by Django 3.2 on 2021-04-29 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_studentregister_gender'),
        ('staff', '0021_auto_20210429_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='standard',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.standard'),
            preserve_default=False,
        ),
    ]
