# Generated by Django 3.2 on 2021-04-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='schoocontact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=15)),
                ('lookingfor', models.CharField(max_length=25)),
                ('massage', models.CharField(max_length=25)),
            ],
        ),
    ]
