# Generated by Django 3.2.6 on 2021-09-20 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmain', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolfeeinfo',
            name='cen_content',
        ),
        migrations.RemoveField(
            model_name='schoolfeeinfo',
            name='cen_image',
        ),
        migrations.RemoveField(
            model_name='schoolfeeinfo',
            name='content1',
        ),
        migrations.RemoveField(
            model_name='schoolfeeinfo',
            name='title1',
        ),
    ]
