# Generated by Django 3.2 on 2021-04-26 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmain', '0003_schoolifo_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolifo',
            old_name='Name',
            new_name='name',
        ),
    ]
