# Generated by Django 3.2 on 2021-05-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmain', '0004_rename_name_schoolifo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolifo',
            name='icon',
            field=models.ImageField(default='thisis', upload_to='schoolinfo'),
            preserve_default=False,
        ),
    ]
