# Generated by Django 3.2.6 on 2021-09-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmain', '0004_auto_20210920_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolfeeinfo',
            name='content2',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolfeeinfo',
            name='content22',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolfeeinfo',
            name='title2',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
