# Generated by Django 3.2.6 on 2021-09-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmain', '0005_auto_20210920_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolfeeinfo',
            name='image2',
            field=models.FileField(default='', upload_to='img'),
            preserve_default=False,
        ),
    ]
