# Generated by Django 3.2.6 on 2021-09-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmain', '0005_schoolifo_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='kidsinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=100)),
                ('s_email', models.EmailField(max_length=254, null=True)),
                ('phone_number', models.IntegerField()),
                ('studying', models.CharField(max_length=500)),
                ('requirement', models.CharField(max_length=150)),
            ],
        ),
    ]
