# Generated by Django 3.2.6 on 2021-09-07 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmain', '0006_kidsinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kidsinfo',
            old_name='s_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='kidsinfo',
            old_name='s_name',
            new_name='name',
        ),
    ]
