# Generated by Django 3.2.6 on 2021-09-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmain', '0007_auto_20210920_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolfeeinfo',
            name='content4',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolfeeinfo',
            name='content44',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolfeeinfo',
            name='image4',
            field=models.FileField(default='', upload_to='img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolfeeinfo',
            name='title4',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
