# Generated by Django 3.2.6 on 2021-09-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmain', '0007_auto_20210907_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kidsinfo',
            old_name='name',
            new_name='kname',
        ),
        migrations.AlterField(
            model_name='kidsinfo',
            name='email',
            field=models.EmailField(default='sa', max_length=254),
            preserve_default=False,
        ),
    ]
