# Generated by Django 3.2.6 on 2021-09-20 07:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmain', '0008_auto_20210920_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolfeeinfo',
            name='content11',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
