# Generated by Django 3.2.6 on 2021-09-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmain', '0008_auto_20210907_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='schoolfeeinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standards', models.CharField(max_length=100)),
                ('annualfee', models.IntegerField()),
            ],
        ),
    ]
