# Generated by Django 3.2.6 on 2022-01-16 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmain', '0010_gallery_galleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='gallery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='GalleryImage', to='schoolmain.gallery'),
            preserve_default=False,
        ),
    ]
