# Generated by Django 3.2.6 on 2021-09-08 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmain', '0010_schoolfeeinfo_yearsormonth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolfeeinfo',
            old_name='yearsormonth',
            new_name='yearlysormonthly',
        ),
    ]
