# Generated by Django 3.2.6 on 2021-09-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmain', '0012_schoolfeeinfo_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=100)),
                ('your_loction', models.CharField(max_length=100)),
                ('looking_for', models.CharField(max_length=50)),
                ('your_message', models.TextField(max_length=500)),
            ],
        ),
    ]
