# Generated by Django 3.2.6 on 2021-09-08 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmain', '0013_contactform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='your_loction',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='contactform',
            old_name='email_address',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contactform',
            old_name='your_message',
            new_name='message',
        ),
    ]
