# Generated by Django 3.2.6 on 2021-09-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmain', '0016_aboutlearning'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolfeeinfo',
            name='slug',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
