# Generated by Django 3.2.6 on 2021-09-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmain', '0019_auto_20210910_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedetails',
            name='content_img',
            field=models.FileField(upload_to='img'),
        ),
        migrations.AlterField(
            model_name='feedetails',
            name='image',
            field=models.FileField(upload_to='img'),
        ),
    ]
