# Generated by Django 3.2.6 on 2021-09-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmain', '0020_auto_20210913_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='admissionform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('contact_no', models.IntegerField()),
                ('messages', models.CharField(max_length=500)),
            ],
        ),
    ]
