# Generated by Django 3.1.7 on 2021-04-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_studentregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregister',
            name='Father_name',
            field=models.CharField(default='noname', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentregister',
            name='Mother_name',
            field=models.CharField(default='noname', max_length=25),
            preserve_default=False,
        ),
    ]
