# Generated by Django 3.1.7 on 2021-04-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20210403_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentregister',
            name='role',
        ),
        migrations.AddField(
            model_name='studentregister',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
