# Generated by Django 3.1.7 on 2021-04-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20210403_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentregister',
            old_name='sssid',
            new_name='ssmid',
        ),
        migrations.AddField(
            model_name='studentregister',
            name='address',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentregister',
            name='permanent_address',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
