# Generated by Django 3.1.7 on 2021-04-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20210403_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregister',
            name='TC',
            field=models.FileField(blank=True, upload_to='certificate'),
        ),
        migrations.AlterField(
            model_name='studentregister',
            name='castcertificate',
            field=models.FileField(blank=True, upload_to='certificate'),
        ),
    ]
