# Generated by Django 3.1.7 on 2021-04-06 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_standard_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='standard',
        ),
        migrations.DeleteModel(
            name='standard',
        ),
        migrations.DeleteModel(
            name='subject',
        ),
    ]
