# Generated by Django 3.1.7 on 2021-04-06 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20210406_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregister',
            name='standard',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.standard'),
            preserve_default=False,
        ),
    ]
