# Generated by Django 3.1.7 on 2021-04-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_studentregister_standard'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregister',
            name='phonestatus',
            field=models.BooleanField(default=False),
        ),
    ]
