# Generated by Django 3.2 on 2021-04-26 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_alter_gender_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregister',
            name='gender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.gender'),
            preserve_default=False,
        ),
    ]
